language: nodejs
sudo: required
services:
  - docker

before_install:
  - docker build -t nodewebsite1 .
  
script:
  - docker run -itd --name traviscontainer nodewebsite1
  - docker ps

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag nodewebsite1 $DOCKER_USER/nodewebsite1:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/nodewebsite1:$TRAVIS_BUILD_NUMBER
